### ISSUE TITLE
TypeError: router.websocket is not a function 

### ISSUE THREAD

**Issue by ehsanzaffar** [amekkawi/express-ws-routes#2]
I am unable to add another route to my existing express app I changed my app.js to include following code 

```
var express = require('express');
...
var wstest = require('./routes/tracingtest');
...
//var app = express();
var app = require('express-ws-routes')();
...
app.use('/wstest', wstest);
```

and my route file tracingtest.js looks like

```
var express = require('express');
var router = express.Router();

router.websocket('/', function(info, cb, next) {
    cb(function(socket) {
        socket.send('connected!');
    });
});
```

But when I Start the app I get this Error

```
/home/ehsan/n_ode/trace_student/routes/tracingtest.js:4
router.websocket('/', function(info, cb, next) {
       ^
TypeError: router.websocket is not a function
    at Object.<anonymous> (/home/ehsan/n_ode/trace_student/routes/tracingtest.js:4:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/ehsan/n_ode/trace_student/app.js:13:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/ehsan/n_ode/trace_student/bin/www:7:11)
    at Module._compile (module.js:435:26)
```

**Comment by amekkawi** [comment]
Hi ehsanzaffar. What version of node and express are you using?

**Comment by ehsanzaffar** [comment]
I am using version 4.13.3 ... 
Sorry for being may be uninformed ... but the latest version of express at npm 4.13.3 .. 
I read the other issue reported and comments as well .. but where could i find express 4.5 or above ??

**Comment by amekkawi** [comment]
The version you are using is fine. Right now you need >=4.5 so 4.13.3 is okay.

The problem is the `var app = require('express-ws-routes')();` needs to be before you start adding websocket routes.

So your code should look like...

``` javascript
var express = require('express');
var app = require('express-ws-routes')();
var wstest = require('./routes/tracingtest');
app.use('/wstest', wstest);
```

Let me know if this fixes it for you!

**Comment by amekkawi** [comment]
Also, if your application requires you to create the detached routers before creating the express app, see the [Manual Setup](https://github.com/amekkawi/express-ws-routes#manual-setup) section in the docs.

For example...

``` javascript
var expressWs = require('express-ws-routes');

// Add websocket support to express (returns the express instance for convenience)
var express = expressWs.extendExpress();

// Get the router before creating the app itself
var wstest = require('./routes/tracingtest');

// Create the express app
va app = express();

// Attach the router to the app
app.use('/wstest', wstest);

var server = http.createServer(app);
server.wsServer = expressWs.createWebSocketServer(server, app);
server.listen(8080, function() {
    console.log('Server listening on port 8080...');
});
```

**Comment by ehsanzaffar** [comment]
Well its still not working for me ... 
Just to be sure that its not something with my existing express app .. I created another Express App with express generators and changed it like..

app.js 

```
var express = require('express');
var app = require('express-ws-routes')();
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', routes);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});

app.websocket('/testws', function(info, cb, next) {
  // `info` is the same as ws's verifyClient 
  console.log(
    'ws req from %s using origin %s',
    info.req.originalUrl || info.req.url,
    info.origin
  );

  // Accept connections by passing a function to cb that will handle the connected websocket 
  cb(function(socket) {
    socket.send('connected!');
  });
});
module.exports = app;
```

I am unable to even connect to socket in directly added routes...
I try to connect to socket at ws://localhost:3000/testws

**Comment by amekkawi** [comment]
Two fixes to make your application work:
1. All non-error routes must be before the 404 route since only error routes will be called after that. So move the websocket route to just below `app.set('view engine', 'jade');`
2. The express app created by `var app = require('express-ws-routes')();` has its own `listen` method that needs to be called instead. Change the `bin/www` file created by the express generator to be something like...

``` javascript
var app = require('../app');
var server = app.listen(port);
server.on('error', ...);
server.on('errlisteningor', ...);
```

The express generator is a common use case so I'm going to update the README to address it.

**Comment by ehsanzaffar** [comment]
Thanks a lot for your help .. with this help i was at last able to get sockets running inside an express app..
but still from with in app.js 
as soon as I detach the router for websocket I get following Error

```
/home/ehsan/n_ode/Tutorials/testWS/testWS4/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

TypeError: Router.use() requires middleware function but got a Object
    at Function.use (/home/ehsan/n_ode/Tutorials/testWS/testWS4/node_modules/express/lib/router/index.js:458:13)
    at EventEmitter.<anonymous> (/home/ehsan/n_ode/Tutorials/testWS/testWS4/node_modules/express/lib/application.js:219:21)
    at Array.forEach (native)
    at EventEmitter.use (/home/ehsan/n_ode/Tutorials/testWS/testWS4/node_modules/express/lib/application.js:216:7)
    at Object.<anonymous> (/home/ehsan/n_ode/Tutorials/testWS/testWS4/app.js:43:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

Now my app.js is looking like 

```
var express = require('express');
var app = require('express-ws-routes')();
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');
var testingws2 = require('./routes/testingws');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

app.use('/', routes);
app.use('/users', users);
app.use('/testws2', testingws2);

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));


// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});

module.exports = app;
```

**Comment by amekkawi** [comment]
What line is 458 in index.js? Is it the `app.use('/testws2', testingws2);` line? If so, is `testingws.js` properly exporting an express Router?

For example:

``` javascript
var express = require('express');
var router = express.Router();
router.websocket('/sub/path', function(info, cb, next) {
    cb(function(socket) {
        socket.send('connected!');
    });
});

// You might be missing this line
module.exports = router;
```

**Comment by ehsanzaffar** [comment]
Exactly . I was missing it ...
Thanks  a lot for bearing my stupid questions .. am new to nodejs and express ...
BTW ... Its a great package you wrote ...
