### ISSUE TITLE
The code does not work anymore.

### ISSUE THREAD

**Issue by yiakwy** [amekkawi/express-ws-routes#8]
Modifying Express underlying routers seems to be a good idea. But the code itself does not work any more.

# steps to reproduce the problem

(1) depenancies
1. express version 4.16.3
2. express-ws-route 1.1.0
3. ws 5.1.1

(2) actual output after the server set up and accepts websocket connection from /sim_world

```bash
 express:router dispatching WEBSOCKET /sim_world +33s
  express:router query  : /sim_world +1ms
  express:router expressInit  : /sim_world +0ms
  express:router urlencodedParser  : /sim_world +0ms
  express:router jsonParser  : /sim_world +0ms
  express:router methodOverride  : /sim_world +0ms
  express:router logger  : /sim_world +1ms
  express:router corsMiddleware  : /sim_world +0ms
  express:router serveStatic  : /sim_world +0ms
  express:router <anonymous>  : /sim_world +0ms
  express:router <anonymous>  : /sim_world +0ms
  express:view lookup "error.jade" +1ms
  express:view stat "/Users/lei.wang1/Github/RandomMapGenerator/backend/bin/views/error.jade" +0ms
  express:view render "/Users/lei.wang1/Github/RandomMapGenerator/backend/bin/views/error.jade" +0ms
```

(3) websocket method
```js
app.websocket('/sim_world', function(info, cb ,next){
	cb(function(socket){
		socket.send('connected')

		socket.on('message', function incomingMessage(message){
			socket.send("Thank you very much!")
		})

	})

})

```

I am suspecting that the registration of the method in `Application` and `Router` failed because of this

**Comment by yiakwy** [comment]
Hi @amekkawi I have read all of the source code. The idea is based on express router architecture and  really good compared to "express-ws". 

The only thing I can't get is "verifyClient" part and corresponding "default connection handler". And moreover, the code does not work now.

**Comment by yiakwy** [comment]
By tracing the source code of express, I found something unusual
``` js
[source test] try to match [object Object] with /sim_world
[source-test] executing regexp /^\/sim_world\/?$/i
match result [ '/sim_world',
  [length]: 1,
  index: 0,
  input: '/sim_world',
  groups: undefined ]
got a mtch!
keys [ [length]: 0 ]
params {}
modified params {}
[source-test] there is a pending error, exit.
[source-test] { TypeError: Cannot read property 'length' of null
    at ServerResponse._send (_http_outgoing.js:231:33)
    at write_ (_http_outgoing.js:650:15)
    at ServerResponse.end (_http_outgoing.js:734:5)
    at ServerResponse.send (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/response.js:221:10)
    at done (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/response.js:1004:10)
    at Object.exports.renderFile (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/jade/lib/index.js:374:12)
    at View.exports.__express [as engine] (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/jade/lib/index.js:417:11)
    at View.render (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/response.js:1008:7)
    at /Users/lei.wang1/Github/RandomMapGenerator/backend/src/server.js:86:8
    at Layer.handle_error (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/index.js:321:13)
    at /Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/index.js:290:7
    at Function.process_params (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/index.js:341:12)
  [stack]: 'TypeError: Cannot read property \'length\' of null\n    at ServerResponse._send (_http_outgoing.js:231:33)\n    at write_ (_http_outgoing.js:650:15)\n    at ServerResponse.end (_http_outgoing.js:734:5)\n    at ServerResponse.send (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/response.js:221:10)\n    at done (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/response.js:1004:10)\n    at Object.exports.renderFile (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/jade/lib/index.js:374:12)\n    at View.exports.__express [as engine] (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/jade/lib/index.js:417:11)\n    at View.render (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/view.js:135:8)\n    at tryRender (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/application.js:640:10)\n    at Function.render (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/application.js:592:3)\n    at ServerResponse.render (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/response.js:1008:7)\n    at /Users/lei.wang1/Github/RandomMapGenerator/backend/src/server.js:86:8\n    at Layer.handle_error (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/index.js:321:13)\n    at /Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/index.js:290:7\n    at Function.process_params (/Users/lei.wang1/Github/RandomMapGenerator/backend/node_modules/express/lib/router/index.js:341:12)',
  [message]: 'Cannot read property \'length\' of null' }
this is the end of match
[server:app.handle] enter into
[server:app.handle] already handled
[server:app.handle] exit
[server:onUpgrade] receive websocket connection request [object Object] from /sim_world
```

The server rejects the request before the matched layer

**Comment by yiakwy** [comment]
I finally make it work. The problem is 

```bash
	// THIS WILL TERMINATE WEBSOCKET CONNECTION
	/*
	// catch 404 and forward to error handler
	app.use(function(req, res, next) {
	  next(createError(404))
	})
	*/

	/*
	// error handler
	app.use(function(err, req, res, next) {
	  // set locals, only providing error in development
	  res.locals.message = err.message;
	  res.locals.error = req.app.get('env') === 'development' ? err : {};

	  // render the error page
	  res.status(err.status || 500);
	  res.render('error');
	});
	*/

```
