### ISSUE TITLE
this.ee.on is not a function

### ISSUE THREAD

**Issue by anwarhamr** [amekkawi/express-ws-routes#9]
Hi I'm trying to use your module and getting the above error.  The client makes a successful connection but then I see this error.

{"error":{},"level":"error","message":"uncaughtException: this.ee.on is not a function\nTypeError: this.ee.on is not a function\n    at Ultron.on (/Users/roblingstuyl/_sandbox/mouth/node_modules/ultron/index.js:42:11)\n    at firstHandler (/Users/roblingstuyl/_sandbox/mouth/node_modules/express-ws-routes/node_modules/ws/lib/WebSocket.js:812:12)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","stack":"TypeError: this.ee.on is not a function\n    at Ultron.on (/Users/roblingstuyl/_sandbox/mouth/node_modules/ultron/index.js:42:11)\n    at firstHandler (/Users/roblingstuyl/_sandbox/mouth/node_modules/express-ws-routes/node_modules/ws/lib/WebSocket.js:812:12)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","exception":true,"date":"Tue Oct 02 2018 15:38:39 GMT-0600 (MDT)","process":{"pid":14890,"uid":501,"gid":20,"cwd":"/Users/roblingstuyl/_sandbox/mouth","execPath":"/usr/local/Cellar/node/8.7.0/bin/node","version":"v8.7.0","argv":["/usr/local/Cellar/node/8.7.0/bin/node","/Users/roblingstuyl/_sandbox/mouth/server.js"],"memoryUsage":{"rss":88690688,"heapTotal":69128192,"heapUsed":51200392,"external":18955114}},"os":{"loadavg":[2.19775390625,2.29541015625,2.25927734375],"uptime":105227},"trace":[{"column":11,"file":"/Users/roblingstuyl/_sandbox/mouth/node_modules/ultron/index.js","function":"Ultron.on","line":42,"method":"on","native":false},{"column":12,"file":"/Users/roblingstuyl/_sandbox/mouth/node_modules/express-ws-routes/node_modules/ws/lib/WebSocket.js","function":"firstHandler","line":812,"method":null,"native":false},{"column":7,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":131,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":180,"method":"_tickCallback","native":false}]}

This is my code
```
var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var jsonParser = bodyParser.json({ type: 'application/*+json'});
router.use(bodyParser.urlencoded({ extended: true }));

router.post('/', function (req, res) {
...
});

router.websocket('/', function(info, cb, next) {
  logger.info( `ws req from ${info.req.originalUrl || info.req.url} using origin ${info.origin}` );

  // Accept connections by passing a function to cb that will handle the connected websocket
  cb(function(socket,value) {
    console.log(value);
    socket.on('message', function(msg) {
      console.log(msg);
      socket.send(JSON.stringify({'orig':msg}));
    });
  });
});

module.exports = router;

```

**Comment by anwarhamr** [comment]
After hours of debugging and trying different wireup I finally found the pattern.... I hope it helps someone else.  Please consider adding example to README.
```

router.websocket('/:device', function(info, cb, next) {
  debug( `ws req from ${info.req.originalUrl || info.req.url} using origin ${info.origin}` );

  // Accept connections by passing a function to cb that will handle the connected websocket

  cb(function(socket, a) {
    debug('socket cb',device);
    socket.onmessage = (msg)=>{
      socket.send(JSON.stringify({'message':msg.data}));
      // ensure that you handle errors...
      //socket.send({'this should throw error':msg.data});
    };

    socket.onerror = (msg)=>{
      debug('**************** onerror',msg);
    };

    socket.onclose = (closeEvent)=>{
      debug('**************** onclose',closeEvent);
    };

    socket.send(JSON.stringify({'connected':true}));
  });
});
```
